imports:
    - { resource: parameters.ini }

parameters:
    exception_listener.controller: "OdinoBlogBundle:Exception:exception"

framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        secret: %csrf_secret%
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true
    esi: {}

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false

# Doctrine Configuration
doctrine:
    dbal:
        host:     localhost
        driver:   pdo_mysql
        dbname:   odino
        user:     root
        password: null
        logging:  %kernel.debug%
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        mappings:
          OdinoBlogBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport:  %mailer_transport%
    host:       %mailer_host%
    username:   %mailer_user%
    password:   %mailer_password%
